#!/bin/bash
exec > >(tee -a ./action_PRE-$VMT_TARGET_NAME-$$.log) 2>&1

# AppDynamics API Info: https://docs.appdynamics.com/display/PRO45/Alert+and+Respond+API#AlertandRespondAPI-CreateaCustomEvent
# The message we want to send CWOM recommend to scale up a serve
# Message Severity (INFO, WARN, ERROR)
APPD_MSG_SEVERITY="WARN"
# Must be custom
APPD_MSG_EVENTYPE="CUSTOM"
APPD_MSG_CUSTOM_EVENT_TYPE="CWOM"

# AppD Account to be used by CWOM
APPD_USER_PWD="C1sco123"
APPD_USER_NAME="admin@customer1"

echo "Sending request to AppDynamics for VM " $VMT_TARGET_NAME
echo " - VMT_TARGET_INTERNAL:"$VMT_TARGET_INTERNAL
echo " - VMT_TARGET_NAME:"$VMT_TARGET_NAME
echo " - VMT_CURRENT_INTERNAL:"$VMT_CURRENT_INTERNAL
echo " - VMT_CURRENT_NAME:"$VMT_CURRENT_NAME
echo " - VT_NEW_INTERNAL:"$VT_NEW_INTERNAL
echo " - VMT_NEW_NAME:"$VMT_NEW_NAME
echo " - VMT_ACTION_INTERNAL:"$VMT_ACTION_INTERNAL
echo " - VMT_ACTION_NAME:"$VMT_ACTION_NAME
###### Output Example
# Sending request to AppDynamics
# VMT_TARGET_INTERNAL:vm-826
# VMT_TARGET_NAME:DCSEVT-POD30
# VMT_CURRENT_INTERNAL:null
# VMT_CURRENT_NAME:null
# VT_NEW_INTERNAL:
# VMT_NEW_NAME:null
# VMT_ACTION_INTERNAL:_gSUlwNCVEeiIBpKT3nV3Nw
# VMT_ACTION_NAME:ACTIONITEM-42166bbe-7635-66df-417d-9db34909ab86

# Generating an HTTP POST request to AppDynamics
# Additional details: https://docs.appdynamics.com/display/PRO45/Application+Model+API

# STEP 1: Get the details (text) for the action generated by CWOM
# and associate it to a variable
ACTION_MSG=$(curl -k -X GET https://localhost/vmturbo/rest/actions/$VMT_ACTION_INTERNAL --user administrator:DCSEVT | grep -Po '"details": *\K"[^"]*"'  | cut -f2 -d '"' )

APPD_MSG_SUMMARY="CWOM recomend the following: "$ACTION_MSG

# TRICK. Get the Application ID by 
# we assume we the application name id DCSEVT-PODXX
# awe remove the DCSEVT. text
APP_NAME=$(echo $VMT_TARGET_NAME | grep -oP '(?<='DCSEVT-').*' )

#1 STEP 2Remove - Get Application ID
APPD_ADDR="http://172.16.16.86:8090/controller/rest/applications/"$APP_NAME
APPD_APP_ID=$(curl -X GET --user $APPD_USER_NAME:$APPD_USER_PWD $APPD_ADDR | grep -oP '(?<=<id>).*?(?=</id>)' )

#2 STEP 2 - Get Node Name
# we assume we only have one node for the demo
# and the name is tomcat
APPD_APP_NODE_NAME=$(curl -X GET --user $APPD_USER_NAME:$APPD_USER_PWD $APPD_ADDR/nodes | grep -oP '(?<=<name>).*?(?=</name>)' )

#3 STEP 3 - Get Tier Name
# we assume we only have one tier for the demo
# and the name is DCSEVT-Petclinic
APPD_APP_TIER_NAME=$(curl -X GET --user $APPD_USER_NAME:$APPD_USER_PWD $APPD_ADDR/tiers | grep -oP '(?<=<name>).*?(?=</name>)' )

#STEP 4 - Posting the action to AppDynamics
echo "Posting the event for: AppID="$APPD_APP_ID", NodeName="$APPD_APP_NODE_NAME", TierName="$APPD_APP_TIER_NAME
curl -v -X POST --user $APPD_USER_NAME:$APPD_USER_PWD 'http://172.16.16.86:8090/controller/rest/applications/'$APPD_APP_ID'/events?severity='$APPD_MSG_SEVERITY'&eventtype='$APPD_MSG_EVENTYPE'&customeventtype='$APPD_MSG_CUSTOM_EVENT_TYPE'&node='$APPD_APP_NODE_NAME'&tier='$APPD_APP_TIER_NAME --data-urlencode "summary=$APPD_MSG_SUMMARY"
